// Generated by CoffeeScript 1.4.0
var agent1, agent2, doc1, docred, mockApp, options, redsys, rewire, vfs;

rewire = require("rewire");

redsys = rewire("./redsys.coffee");

options = {
  db: {
    type: 'none'
  },
  browserChannel: null
};

mockApp = {
  on: function() {},
  use: function() {}
};

redsys.attach(mockApp, options);

vfs = {
  stat: function(file, opt, callback) {
    var _ref;
    return callback((_ref = !file) === "test1.tex" || _ref === "test2.txt" ? "not found" : void 0);
  },
  read: function(file, opt, callback) {
    var _ref;
    return callback((_ref = !file) === "test1.tex" || _ref === "test2.txt" ? "not found" : void 0);
  }
};

redsys.createProject(vfs, "testproject");

agent1 = {
  headers: {
    cookie: "abc1"
  }
};

agent2 = {
  headers: {
    cookie: "abc2"
  }
};

doc1 = {
  docName: "testproject/test1.tex",
  type: "read"
};

docred = {
  docName: "__REDSYS__",
  op: [
    {
      i: JSON.stringify({
        action: "setProject",
        project_id: "testproject"
      })
    }
  ],
  accept: function() {},
  reject: function() {}
};

options.auth(agent2, docred);

exports.test_open_without_project = function(test) {
  doc1.accept = function() {
    return test.ok(false, "false");
  };
  doc1.reject = function() {
    return test.ok(true, "true");
  };
  options.auth(agent1, doc1);
  return test.done();
};

exports.test_open_with_project = function(test) {
  doc1.accept = function() {
    return test.ok(true, "true");
  };
  doc1.reject = function() {
    return test.ok(false, "false");
  };
  options.auth(agent2, doc1);
  return test.done();
};
