// Generated by CoffeeScript 1.4.0
var AttributePool, Changeset, S, agentToProject, async, auth, created, default_text_format, handle_redsys, hat, model, projects, sharejs, updateIfNecessary, valid_file;

default_text_format = "etherpad";

sharejs = require("share").server;

Changeset = require("share").types.etherpad.Changeset;

AttributePool = require("share").types.etherpad.AttributePool;

projects = {};

hat = require("hat");

async = require("async");

S = require("string");

created = {};

agentToProject = {};

model = null;

handle_redsys = function(agent, msg) {
  var action;
  action = msg.action;
  if (action === "setProject") {
    if (!(projects[msg.project_id] != null)) {
      return;
    }
    console.log(agent.sessionId, "assigned to ", msg.project_id);
    return agentToProject[agent.headers.cookie] = {
      project: msg.project_id,
      vfs: projects[msg.project_id]
    };
  }
};

updateIfNecessary = function(docName, initValueCallback, callback) {
  async.waterfall([
    function(callback) {
      return model.create(docName, default_text_format, {}, callback);
    }, function(callback) {
      return initValueCallback(callback);
    }, function(doc, callback) {
      var op;
      op = {};
      op.pool = new AttributePool();
      op.changeset = Changeset.builder(0).insert(doc, "", op.pool).toString();
      return model.applyOp(docName, {
        "op": op,
        v: 0
      }, callback);
    }
  ], function(err) {
    return console.log(err);
  });
  return callback();
};

valid_file = function(fileName, vfs, callback) {
  return vfs.stat(fileName, {}, callback);
};

auth = function(agent, action) {
  var docName, projectData, readFile, vfs, _ref, _ref1, _ref2;
  if (action.docName === "__REDSYS__") {
    if (action.op != null) {
      handle_redsys(agent, JSON.parse(action.op[0].i));
      return action.reject();
    } else {
      return action.accept();
    }
  }
  if ((_ref = action.name) === "connect") {
    return action.accept();
  }
  if (!(agentToProject[agent.headers.cookie] != null)) {
    return action.reject();
  }
  projectData = agentToProject[agent.headers.cookie];
  if (!S(action.docName).startsWith(projectData.project)) {
    return action.reject();
  }
  docName = action.docName.replace("::", "/").slice(projectData.project.length);
  vfs = projectData.vfs;
  readFile = function(callback) {
    return async.waterfall([
      function(callback) {
        return vfs.readfile(docName, {}, callback);
      }, function(data, callback) {
        var file;
        file = "";
        data.stream.on("data", function(str) {
          return file += str.toString();
        });
        return data.stream.on("end", function() {
          return callback(null, file);
        });
      }
    ], callback);
  };
  if (((_ref1 = action.type) === "create" || _ref1 === "read") && !(created[docName] != null)) {
    console.log("creating...");
    async.waterfall([
      function(callback) {
        return valid_file(docName, vfs, callback);
      }, function(stat, callback) {
        return updateIfNecessary(action.docName, readFile, callback);
      }, function(callback) {
        created[docName] = true;
        action.accept();
        return callback();
      }
    ], function(err) {
      if (err) {
        return action.reject();
      }
    });
    return;
  }
  if ((_ref2 = action.type) === "update" || _ref2 === "create" || _ref2 === "read") {
    valid_file(docName, vfs, function(err) {
      if (err) {
        return action.reject();
      }
      return action.accept();
    });
    return;
  }
  console.log("What does ", action.type, "mean?");
  return action.reject();
};

exports.attach = function(app, options) {
  options.auth = auth;
  if (!(model != null)) {
    model = sharejs.createModel(options);
  }
  return sharejs.attach(app, options, model);
};

exports.createProject = function(vfs, project_id) {
  if (project_id == null) {
    project_id = hat();
  }
  projects[project_id] = vfs;
  return console.log("project " + project_id + " was generated");
};
